version: "3.9"
services:
  flaskServer:
    build:
      context: .
      dockerfile: flask.Dockerfile
    image: shay79il/flaskgame
    ports:
      - "8777:5000"
    volumes:
      - ./Text_files/Scores.txt:/home/app/Text_files/Scores.txt
